### ISSUE TITLE
API changes and node-client

### ISSUE THREAD

**Issue by snoe** [neovim/node-host#17]
It looks like host is behind node-client (2.1.0) again, but there have also been a lot of neovim api changes recently (at least up to https://github.com/neovim/neovim/pull/5344) and I'm not entirely sure that node-client is up to date. It would be good to bump the node-client version in this repo if that's all it takes to keep up with neovim.

**Comment by justinmk** [comment]
Latest `nvim` should be compatible with old clients. What error are you seeing?

**Comment by snoe** [comment]
It looks like bumping node-client to 2.1.0 might be sufficient. The error (after putting in a try/catch and print) was missing `Nvim` in the `types` object parsed from `get_api_info`

``````
{ Buffer: [Function: Buffer],
  Window: [Function: Window],
  Tabpage: [Function: Tabpage] }

TypeError: Cannot read property 'prototype' of undefined
    at generateWrappers (/Users/case/.vim/bundle/node-host/node_modules/neovim-client/index.js:80:9)
    at /Users/case/.vim/bundle/node-host/node_modules/neovim-client/index.js:178:5
    at Session._parse_message (/Users/case/.vim/bundle/node-host/node_modules/msgpack5rpc/index.js:96:5)
    at Decoder.<anonymous> (/Users/case/.vim/bundle/node-host/node_modules/msgpack5rpc/index.js:42:11)
    at emitOne (events.js:90:13)
    at Decoder.emit (events.js:182:7)
    at readableAddChunk (/Users/case/.vim/bundle/node-host/node_modules/readable-stream/lib/_stream_readable.js:213:18)
    at Decoder.Readable.push (/Users/case/.vim/bundle/node-host/node_modules/readable-stream/lib/_stream_readable.js:172:10)
    at Decoder.Transform.push (/Users/case/.vim/bundle/node-host/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at Decoder._transform (/Users/case/.vim/bundle/node-host/node_modules/msgpack5/lib/streams.js:65:10)```
``````

**Comment by nhynes** [comment]
Gee, wouldn't it be great if `node-host` automatically got updated with `node-client` without having to depend on the master branch?

**Comment by snoe** [comment]
node-client was bumped and it seems like everything is working again. Thanks!
