### ISSUE TITLE
version fails to fetch

### ISSUE THREAD

**Issue by SevereOverfl0w** [neovim/node-host#28]
```
❯ /usr/bin/neovim-node-host --version          
module.js:487
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/neovim/lib/host/factory.js:7:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by billyvg** [comment]
Odd, I just pushed `3.4.5` that should fix the lodash dependency.

**Comment by SevereOverfl0w** [comment]
Fixed, thanks!
